
/**************************************************************
 *	
 *	Applause, 8 bit, 11025Hz,
 *	1 channel, 83878 bytes/channel
 *	Total Size: 1 * 83878 + 4 (header) = 83922 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/eunjikang/Desktop/SPR19/CS2261/Milestones/M03/Applause.wav
 *	Time-stamp: Sun Apr 21 13:13:25 2019
 *	
 **************************************************************/

#ifndef __APPLAUSEH__
#define __APPLAUSEH__

#define APPLAUSEFREQ 11025
#define APPLAUSELEN 83878

extern const unsigned char Applause[83878];

#endif /* __APPLAUSEH__ */
