
/**************************************************************
 *	
 *	sadTrombone, 8 bit, 11025Hz,
 *	1 channel, 46368 bytes/channel
 *	Total Size: 1 * 46368 + 4 (header) = 46412 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/eunjikang/Desktop/SPR19/CS2261/Milestones/M03/sadTrombone.wav
 *	Time-stamp: Sun Apr 21 13:12:36 2019
 *	
 **************************************************************/

#ifndef __SADTROMBONEH__
#define __SADTROMBONEH__

#define SADTROMBONEFREQ 11025
#define SADTROMBONELEN 46368

extern const unsigned char sadTrombone[46368];

#endif /* __SADTROMBONEH__ */
